namespace ICC.Net
{
    public abstract class TagSignatures
    {
        public const TagSignature AToB0Tag = TagSignature.AToB0Tag;
        public const TagSignature AToB1Tag = TagSignature.AToB1Tag;
        public const TagSignature AToB2Tag = TagSignature.AToB2Tag;
        public const TagSignature BlueColorantTag = TagSignature.BlueColorantTag;
        public const TagSignature BlueTrcTag = TagSignature.BlueTrcTag;
        public const TagSignature BToA0Tag = TagSignature.BToA0Tag;
        public const TagSignature BToA1Tag = TagSignature.BToA1Tag;
        public const TagSignature BToA2Tag = TagSignature.BToA2Tag;
        public const TagSignature BToD0Tag = TagSignature.BToD0Tag;
        public const TagSignature BToD1Tag = TagSignature.BToD1Tag;
        public const TagSignature BToD2Tag = TagSignature.BToD2Tag;
        public const TagSignature BToD3Tag = TagSignature.BToD3Tag;
        public const TagSignature CalibrationDateTimeTag = TagSignature.CalibrationDateTimeTag;
        public const TagSignature CharTargetTag = TagSignature.CharTargetTag;
        public const TagSignature ChromaticAdaptionTag = TagSignature.ChromaticAdaptionTag;
        public const TagSignature ChromaticityTag = TagSignature.ChromaticityTag;
        public const TagSignature ColorantOrderTag = TagSignature.ColorantOrderTag;
        public const TagSignature ColorantTableOutTag = TagSignature.ColorantTableOutTag;
        public const TagSignature ColorantTableTag = TagSignature.ColorantTableTag;
        public const TagSignature CopyrightTag = TagSignature.CopyrightTag;
        public const TagSignature DeviceMfgDescTag = TagSignature.DeviceMfgDescTag;
        public const TagSignature DeviceModelDescTag = TagSignature.DeviceModelDescTag;
        public const TagSignature DToB0Tag = TagSignature.DToB0Tag;
        public const TagSignature DToB1Tag = TagSignature.DToB1Tag;
        public const TagSignature DToB2Tag = TagSignature.DToB2Tag;
        public const TagSignature DToB3Tag = TagSignature.DToB3Tag;
        public const TagSignature GamutTag = TagSignature.GamutTag;
        public const TagSignature GrayTrcTag = TagSignature.GrayTrcTag;
        public const TagSignature GreenColorantTag = TagSignature.GreenColorantTag;
        public const TagSignature GreenTrcTag = TagSignature.GreenTrcTag;
        public const TagSignature LuminanceTag = TagSignature.LuminanceTag;
        public const TagSignature MeasurementTag = TagSignature.MeasurementTag;
        public const TagSignature MediaBlackPointTag = TagSignature.MediaBlackPointTag;
        public const TagSignature MediaWhitePointTag = TagSignature.MediaWhitePointTag;
        public const TagSignature MetaDataTag = TagSignature.MetaDataTag;
        public const TagSignature NamedColor2Tag = TagSignature.NamedColor2Tag;
        public const TagSignature OutputResponseTag = TagSignature.OutputResponseTag;
        public const TagSignature PerceptualRenderingIntentGamutTag = TagSignature.PerceptualRenderingIntentGamutTag;
        public const TagSignature Preview0Tag = TagSignature.Preview0Tag;
        public const TagSignature Preview1Tag = TagSignature.Preview1Tag;
        public const TagSignature Preview2Tag = TagSignature.Preview2Tag;
        public const TagSignature PrintConditionTag = TagSignature.PrintConditionTag;
        public const TagSignature ProfileDescriptionTag = TagSignature.ProfileDescriptionTag;
        public const TagSignature ProfileSequenceDescTag = TagSignature.ProfileSequenceDescTag;
        public const TagSignature ProfileSequenceIdTag = TagSignature.ProfileSequenceIdTag;
        public const TagSignature RedColorantTag = TagSignature.RedColorantTag;
        public const TagSignature RedTrcTag = TagSignature.RedTrcTag;
        public const TagSignature SaturationRenderingIntentGamutTag = TagSignature.SaturationRenderingIntentGamutTag;
        public const TagSignature TechnologyTag = TagSignature.TechnologyTag;
        public const TagSignature ViewingCondDescTag = TagSignature.ViewingCondDescTag;
        public const TagSignature ViewingConditionsTag = TagSignature.ViewingConditionsTag;
        public static string GetName(TagSignature sig) =>
            sig switch
            {
                TagSignature.AToB0Tag => "AToB0Tag",
                TagSignature.AToB1Tag => "AToB1Tag",
                TagSignature.AToB2Tag => "AToB2Tag",
                TagSignature.BlueColorantTag => "blueColorantTag",
                TagSignature.BlueTrcTag => "blueTrcTag",
                TagSignature.BToA0Tag => "BToA0Tag",
                TagSignature.BToA1Tag => "BToA1Tag",
                TagSignature.BToA2Tag => "BToA2Tag",
                TagSignature.BToD0Tag => "BToD0Tag",
                TagSignature.BToD1Tag => "BToD1Tag",
                TagSignature.BToD2Tag => "BToD2Tag",
                TagSignature.BToD3Tag => "BToD3Tag",
                TagSignature.CalibrationDateTimeTag => "calibrationDateTimeTag",
                TagSignature.CharTargetTag => "charTargetTag",
                TagSignature.ChromaticAdaptionTag => "chromaticAdaptationTag",
                TagSignature.ChromaticityTag => "chromaticityTag",
                TagSignature.ColorantOrderTag => "colorantOrderTag",
                TagSignature.ColorantTableOutTag => "colorantTableOutTag",
                TagSignature.ColorantTableTag => "colorantTableTag",
                TagSignature.CopyrightTag => "copyrightTag",
                TagSignature.CrdInfoTag => "crdInfoTag",
                TagSignature.DataTag => "dataTag",
                TagSignature.DateTimeTag => "dateTimeTag",
                TagSignature.DeviceMfgDescTag => "deviceMfgDescTag",
                TagSignature.DeviceModelDescTag => "deviceModelDescTag",
                TagSignature.DeviceSettingsTag => "deviceSettingsTag",
                TagSignature.DToB0Tag => "DToB0Tag",
                TagSignature.DToB1Tag => "DToB1Tag",
                TagSignature.DToB2Tag => "DToB2Tag",
                TagSignature.DToB3Tag => "DToB3Tag",
                TagSignature.GamutTag => "gamutTag",
                TagSignature.GrayTrcTag => "grayTRCTag",
                TagSignature.GreenColorantTag => "greenColorantTag",
                TagSignature.GreenTrcTag => "greenTRCTag",
                TagSignature.LuminanceTag => "luminanceTag",
                TagSignature.MeasurementTag => "measurementTag",
                TagSignature.MediaBlackPointTag => "mediaBlackPointTag",
                TagSignature.MediaWhitePointTag => "mediaWhitePointTag",
                TagSignature.MetaDataTag => "metaDataTag",
                TagSignature.NamedColorTag => "namedColorTag",
                TagSignature.NamedColor2Tag => "namedColor2Tag",
                TagSignature.OutputResponseTag => "outputResponseTag",
                TagSignature.PerceptualRenderingIntentGamutTag => "perceptualRenderingIntentGamutTag",
                TagSignature.Preview0Tag => "preview0Tag",
                TagSignature.Preview1Tag => "preview1Tag",
                TagSignature.Preview2Tag => "preview2Tag",
                TagSignature.PrintConditionTag => "printConditionTag",
                TagSignature.ProfileDescriptionTag => "profileDescriptionTag",
                TagSignature.ProfileSequenceDescTag => "profileSequenceDescTag",
                TagSignature.ProfileSequenceIdTag => "profileSequenceIdentifierTag",
                TagSignature.Ps2Crd0Tag => "ps2CRD0Tag",
                TagSignature.Ps2Crd1Tag => "ps2CRD1Tag",
                TagSignature.Ps2Crd2Tag => "ps2CRD2Tag",
                TagSignature.Ps2Crd3Tag => "ps2CRD3Tag",
                TagSignature.Ps2CsaTag => "ps2CSATag",
                TagSignature.Ps2RenderingIntentTag => "ps2RenderingIntentTag",
                TagSignature.RedColorantTag => "redColorantTag",
                TagSignature.RedTrcTag => "redTRCTag",
                TagSignature.SaturationRenderingIntentGamutTag => "saturationRenderingIntentGamutTag",
                TagSignature.ScreeningDescTag => "screeningDescTag",
                TagSignature.ScreeningTag => "screeningTag",
                TagSignature.TechnologyTag => "technologyTag",
                TagSignature.UcrbgTag => "ucrBgTag",
                TagSignature.ViewingCondDescTag => "viewingCondDescTag",
                TagSignature.ViewingConditionsTag => "viewingConditionsTag",
                _ => "",
            };
    }
}
